### PR TITLE
Fill in the "unknown46" field in the structure document.

### PR DESCRIPTION
**Pull request by no-more-secrets**
These 32 bytes hold common internal state for computing prices of goods in price groups (used for all nations), at least for the four processed goods (rum/coats/cloth/cigars).  For all other goods, the bytes do change, but it appears that their values are not used by the game, at least for computing prices (they could be used for other things unrelated to prices).

### CODE REVIEW

**Comment by TheRealAyCe** [comment]
Do you have a link for the Strategy Guide?

**Comment by no-more-secrets** [comment]
The strategy guide was published as a book around the time that the game was released.  If you do some Google searching I think there is a PDF version floating around, but I don't have the link any longer.

I'd recommend finding it.

But note that the strategy guide doesn't go into detail on how the price groups works, it just briefly mentions them and gives vague statements on what they are.  Pretty much everything that I know about them I found through experimentation and looking at save files.

**Comment by pavelbel** [comment]
Hi @no-more-secrets !

Thanks for you contribution. It's an interesting study. So these values are common to all nations. Does it mean, that in different games all nations' prices dynamic can be somewhat different? Do you have this formula you are talking about?

About merging: it seems to me that it's not a best thing to have such long comments (hints) inside a JSON file (considering that the creator of JSON format intentionally excluded commenting feature). Could you please reduce it to 2 or 3 lines? I'll approve it.

P.S. May be it may be better to have a hyperlink inside hint leading to a full field's description.

**Comment by TheRealAyCe** [comment]
> The strategy guide was published as a book around the time that the game was released. If you do some Google searching I think there is a PDF version floating around, but I don't have the link any longer.
> 
> I'd recommend finding it.

I did and uploaded it here: https://archive.org/details/sid-meier-s-colonization-official-strategy-guide

**Comment by no-more-secrets** [comment]
@pavelbel I've moved most of the comments into a separate file and referenced it from the json file.  Let me know if you like this.

The formula used to compute the prices of those goods requires another input, which is the per-nation inputs that represent how much of each good has been bought/sold by that nation.  Strangely, the current structure document does not seem to contain them, or even contain space for them.  I'm going to go back and track those down again (it's been a couple of years) and then will send another PR, that way we will have all of the inputs to the price group formula.  Actually, those other inputs are needed for computing the prices of the other (non price-group) goods as well.

**Comment by no-more-secrets** [comment]
BTW, if you want to experiment with those price group values, here are some points to keep in mind:
* Those internal price group state values do not change when the net amount that you've purchased is positive; they only change when the net amount you've sold is negative.  This was probably done so that if the player buys one good to e.g. trade with the natives that it won't cause the others' prices to fall.
* The way I get the game to change those values is to create a new game, enter cheat mode, create a colony and load a ship with a bunch of them, then go to europe and sell them, that way you've sold a net positive amount and you'll see those numbers change.
* You can also modify those numbers yourself in the save file; if you do, I believe it won't cause an immediate price change, it will cause the prices to shift over the next few turns, and they should do so in the opposite direction that you changed them.  So if you increase the value for cloth, then it should cause the price of cloth to decrease while the others increase.

**Comment by TheRealAyCe** [comment]
Regarding price groups, I found this in `NAMES.TXT`.
Check out Rise and Fall, it sounds to me like there are multiple "traffic indicator" counters and these fields define which counter makes the price go up and down. Not sure how that works, but maybe it corresponds to your savegame observations. Or maybe that's something else entirely.
```
;
;       Cargo types & economic model
;
;       Economy: start1, 2, low, high, burden, rise, fall, attrition, volatility
;
;       Start 1, 2      = Starting cargo price (lowest/highest)
;       Low             = Lowest possible drift
;       High            = Highest possible drift
;       Burden          = Extra difference between ask & bid prices
;                         (0 means ask is 1 higher than bid)
;       Rise            = Price rises at this traffic indicator
;       Fall            = Price falls at this traffic indicator
;       Attrition       = Amount added to traffic volume each turn
;                         (represents ability of price to recover)
;       Volatility      = Shift value for traffic volume
;

@CARGO
Food,         1,  3,  1,  6,  7,  3,  2, -1,  0
Sugar,        4,  7,  3,  7,  1,  4,  6, -8,  1
Tobacco,      3,  5,  2,  5,  1,  4,  8,-10,  1
Cotton,       2,  5,  2,  5,  1,  4,  6,-11,  1
Furs,         4,  6,  2,  6,  1,  4, 20,-13,  1
Lumber,       2,  2,  2,  2,  4,  3,  2,  0,  0
Ore,          3,  6,  2,  6,  2,  2,  4, -7,  0
Silver,      20, 20,  2, 20,  0,  8,  1, -8,  2
Horses,       2,  3,  2, 11,  0,  3,  2, -3,  0
Rum,         11, 13,  1, 20,  0,  4,  4,-12,  1
Cigars,      11, 13,  1, 20,  0,  4,  4,-11,  1
Cloth,       11, 13,  1, 20,  0,  4,  4,-13,  1
Coats,       11, 13,  1, 20,  0,  4,  4,-11,  1
Trade Goods,  2,  3,  2, 12,  0,  2,  3,  4,  0
Tools,        2,  2,  2,  9,  0,  2,  2,  5,  0
Muskets,      3,  3,  2, 20,  0,  2,  2,  6,  0
```

**Comment by no-more-secrets** [comment]
@pavelbel Yes you are correct those parameters are inputs into the price calculations.  However, they are used differently depending on whether the good is in a price group or not.  Here are the details:
* Start 1, 2: not used by price group, used by all others.
* Low/High: not used by price group, used by all others.
* Burden: used by all goods.  Determines buy/sell spread.
* Rise/Fall: used by all goods, but goods in price groups use them differently since the formula is quite different.
* Attrition: not used by price group, used by all others.  Goods in price group use a different formula for price drift.
* Used by all goods, but used in a different way by price group goods.  This is a "bit shift".  E.g., when you buy 100 silver the price moves (over the course of a few turns) as if you bought 100*(1 << 2)=400 of a good with 0 volatility.

**Comment by no-more-secrets** [comment]
@pavelbel If you don't mind, I also fixed a couple of spacing issues in the structure document in this PR (there were some trailing spaces).

**Comment by pavelbel** [comment]
@no-more-secrets, yes, it's ok. I'm ready to accept your PR, but I're still commiting. Tell me when you're ready pls

**Comment by no-more-secrets** [comment]
@pavelbel Ok finally ready! :-)

**Review by pavelbel — APPROVED** [review]
Ok

**Pull request merged**
