### PR TITLE
Fill in the map connectivity sections and add supplemental info.

### PR DESCRIPTION
**Pull request by no-more-secrets**
See supplemental info for description of the new fields.

Also a couple of other fields in their vicinity are filled in as well, such as the `strategy` field.

### CODE REVIEW

**Comment by no-more-secrets** [comment]
@pavelbel This PR contains the connectivity fields and also a thorough description of the algorithm used to compute them.  That way, if someone wants to generate a tool that modifies the map in a sav file, they will be able to update the connectivity data.

**Comment by pavelbel** [comment]
Hi and happy New Year! I've been busy with NY etc. I'll study your results and the description in supp info. Though I'm sure you are accurate and convincing as usual. I think I'll also add a compact representation for the connectivity data (because I always keep in mind manual editing of SAV.json files)

**Comment by pavelbel** [comment]
Still cannot invent some good compact representation for connectivity fields. So I'll merge it as is.

**Review by pavelbel — APPROVED** [review]
Good, but not compact. I'll fix it myself

**Pull request merged**
